apiVersion: v1
kind: Pod
metadata:
  name: kaniko-builder
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
      - "--dockerfile=Dockerfile"
      - "--context=git://github.com/vtqveant/manifold-indexer-job.git#refs/heads/main"
      - "--destination=harbor.eventflow.ru/library/manifold-indexer-job:latest"
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 500Mi
    volumeMounts:
      - name: config-json
        mountPath: /kaniko/.docker
  volumes:
    - name: config-json
      secret:
        secretName: registry-3
        items:
          - key: .dockerconfigjson
            path: config.json
  restartPolicy: Never
